<?php

use UBOS\Shape\Utility\TcaUtility as Util;

return [
	'label' => 'label',
	'title' => Util::t('field.ctrl.title'),
	'formattedLabel_userFunc' => \UBOS\Shape\UserFunctions\Tca::class . '->getFormattedFieldLabel',
	'tstamp' => 'tstamp',
	'crdate' => 'crdate',
	'origUid' => 't3_origuid',
	'sortby' => 'sorting',
	'delete' => 'deleted',
	'versioningWS' => true,
	'languageField' => 'sys_language_uid',
	'transOrigPointerField' => 'l10n_parent',
	'transOrigDiffSourceField' => 'l10n_diffsource',
	'translationSource' => 'l10n_source',
	'iconfile' => 'EXT:core/Resources/Public/Icons/T3Icons/svgs/form/form-text.svg',
	'enablecolumns' => [
		'disabled' => 'hidden',
	],
	'searchFields' => 'label,description',
	'type' => 'type',
	'typeicon_column' => 'type',
	'typeicon_classes' => [
		'default' => 'form-text',
		'text' => 'form-text',
		'textarea' => 'form-textarea',
		'checkbox' => 'form-checkbox',
		'select' => 'form-single-select',
		'radio' => 'form-radio-button',
		'multi-checkbox' => 'form-multi-checkbox',
		'multi-select' => 'form-multi-select',
		'country-select' => 'form-single-select',
		'email' => 'form-email',
		'number' => 'form-number',
		'tel' => 'form-telephone',
		'password' => 'form-password',
		'search' => 'form-text',
		'url' => 'form-url',
		'color' => 'form-text',
		'range' => 'form-text',
		'date' => 'form-date-picker',
		'datetime-local' => 'form-date-picker',
		'time' => 'form-date-picker',
		'week' => 'form-date-picker',
		'month' => 'form-date-picker',
		'file' => 'form-file-upload',
		'reset' => 'form-text',
		'captcha' => 'form-text',
		'hidden' => 'form-hidden',
		'content-header' => 'content-header',
		'content-rte' => 'form-static-text',
		'content-element' => 'form-content-element',
		'repeatable-container' => 'content-container',
	],
];